"""Generated docs must match the sources they claim to be generated from.

`docs/BOUNDS.md` says at the top: "Generated by `tools/gen_docs.py` from
`agent/bounds/rules.yaml`. Do not hand-edit." That header is a promise to a
reader that the table below it is what the gate actually enforces.

It was broken. `PROMISE_COOLDOWN` was changed in `rules.yaml` (WHAT_BROKE
#14) and the doc was not regenerated, so `docs/BOUNDS.md` published the old
rule text -- a document whose entire value is being derivable from source,
quietly not derivable from source.

The uncomfortable part: `gen_docs.py --check` already existed, and did
exactly this job, correctly, including the distinction between
deterministic generators and `LEDGER.md` (whose hash chain legitimately
differs every run). Nothing ever invoked it -- not CI, not the suite. The
tool was built and never wired up, which is a more common failure than a
missing tool and harder to notice, because the capability is right there in
the repo looking finished.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[1]


def _all_rules() -> list[dict]:
    """Both registers. rules.yaml splits them -- `regulatory` (law this
    system must not break) and `stopping` (limits it imposes on itself) --
    and a check that read one and not the other would pass while half the
    gate drifted."""
    loaded = yaml.safe_load((REPO / "agent" / "bounds" / "rules.yaml").read_text(encoding="utf-8"))
    return list(loaded["regulatory"]) + list(loaded["stopping"])


def test_gen_docs_check_reports_no_stale_documents():
    """The repo's own staleness check, finally run by something.

    `--check` compares without writing, so this asserts on the working tree
    rather than quietly repairing it -- a test that regenerates the docs it
    is checking would pass forever and detect nothing.
    """
    result = subprocess.run(
        [sys.executable, str(REPO / "tools" / "gen_docs.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "tools/gen_docs.py --check reports stale generated documentation:\n"
        f"{result.stdout}\n{result.stderr}\n"
        "Run `python tools/gen_docs.py` and commit the result."
    )


def test_every_bounds_rule_id_appears_in_the_generated_table():
    """A rule added to the YAML and never regenerated into the doc leaves
    the doc claiming the gate has fewer rules than it does. Independent of
    the generator, so it still holds if `--check` is ever weakened."""
    ids = [r["id"] for r in _all_rules()]
    published = (REPO / "docs" / "BOUNDS.md").read_text(encoding="utf-8")

    missing = [rule_id for rule_id in ids if f"`{rule_id}`" not in published]
    assert not missing, f"docs/BOUNDS.md does not mention {missing} -- regenerate it"


def test_the_published_rule_text_matches_the_yaml():
    """The exact failure from WHAT_BROKE #14: the rule was edited, the doc
    was not regenerated, and the published `machine:` expression was the old
    one. Compares the collapsed expression, since the generator folds
    whitespace into a table cell (WHAT_BROKE #5)."""
    published = (REPO / "docs" / "BOUNDS.md").read_text(encoding="utf-8")

    stale = []
    for rule in _all_rules():
        expected = re.sub(r"\s+", " ", str(rule["machine"])).strip()
        if expected not in published:
            stale.append(rule["id"])
    assert not stale, (
        f"docs/BOUNDS.md publishes different rule text than agent/bounds/rules.yaml "
        f"for {stale}. Run `python tools/gen_docs.py`."
    )


def test_the_check_does_not_rewrite_the_working_tree():
    """`--check` must compare, not repair. A check that fixes what it finds
    turns a staleness failure into a silent working-tree edit, and the first
    version of this very test did exactly that by passing an argument
    `gen_docs.py` ignores."""
    bounds = REPO / "docs" / "BOUNDS.md"
    before = bounds.read_text(encoding="utf-8")
    subprocess.run(
        [sys.executable, str(REPO / "tools" / "gen_docs.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert bounds.read_text(encoding="utf-8") == before


def test_results_md_matches_what_the_eval_actually_produces():
    """The one generated doc `gen_docs.py --check` never covered.

    RESULTS.md is produced by `eval/report.py`, not `tools/gen_docs.py`, so
    it sat outside the gate -- and drifted. #12, #14 and #17 changed
    escalation and attribution behaviour, the eval moved under the doc, and
    the committed numbers went stale (Arm C escalation 9.6% -> 8.0%, mean
    touches 1.78 -> 1.80, every lift-sweep row shifted). The headline
    claims held, which is exactly why nobody noticed.

    This is the document the README invites a reader to reproduce, so it is
    the worst one to leave ungated. Verified deterministic: two consecutive
    runs are byte-identical.

    Slower than the rest of this file because it runs the real harness. It
    is worth it -- a judge running the documented command and getting a
    diff costs more than the seconds this takes.
    """
    result = subprocess.run(
        [sys.executable, str(REPO / "eval" / "report.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "docs/RESULTS.md is stale with respect to eval/report.py:\n"
        f"{result.stdout}\n{result.stderr}\n"
        "Run `python eval/report.py` and commit the result."
    )


def test_extraction_accuracy_matches_what_the_scorer_produces():
    """The third generated results document, gated on arrival rather than
    after it drifts.

    RESULTS.md went stale because it sat outside the gate (#18), and the
    lesson recorded there was that gating one results doc and not another
    is exactly how the first one drifts. So this one is gated in the same
    commit that creates it, before it has had a chance to.

    It also gates something the other two do not: a stale
    EXTRACTION_ACCURACY.md could publish a *different accuracy figure* than
    the committed run in golden_extractor_results.json actually produced,
    which is the specific way a pre-registered result stops meaning
    anything. Cheap to check -- no model calls, both result sets are
    cached.
    """
    result = subprocess.run(
        [sys.executable, "-m", "eval.golden.score", "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "docs/evidence/EXTRACTION_ACCURACY.md is stale with respect to "
        f"eval/golden/score.py:\n{result.stdout}\n{result.stderr}\n"
        "Run `python -m eval.golden.score --report` and commit the result."
    )


def test_the_golden_labels_are_committed_before_the_results_they_score():
    """Pre-registration, asserted rather than trusted.

    The whole claim of EXTRACTION_ACCURACY.md rests on replies.jsonl being
    committed before the extractor ran against it. `score.py` enforces that
    at run time; this asserts the enforcement is actually reachable and has
    not been quietly disabled -- and it fails loudly on a shallow clone
    instead of passing for the wrong reason, which is the trap that made
    eleven red CI runs report green (WHAT_BROKE #22).
    """
    from eval.golden.score import PreregistrationViolation, verify_preregistration

    try:
        commit = verify_preregistration()
    except PreregistrationViolation as exc:
        pytest.fail(f"golden-set pre-registration is not intact: {exc}")
    assert len(commit) == 40, "expected a full commit sha for the label commit"


def test_results_family_b_matches_what_its_eval_produces():
    """The second pre-registered run's results, gated like the first.

    Two generated results documents now exist and both are things a reader
    is invited to reproduce, so both are checked. Gating one and not the
    other is how the first one drifted (WHAT_BROKE #18)."""
    result = subprocess.run(
        [sys.executable, str(REPO / "eval" / "report_family_b.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "docs/RESULTS_FAMILY_B.md is stale with respect to eval/report_family_b.py:\n"
        f"{result.stdout}\n{result.stderr}\n"
        "Run `python eval/report_family_b.py` and commit the result."
    )
