"""Generated docs must match the sources they claim to be generated from.

`docs/BOUNDS.md` says at the top: "Generated by `tools/gen_docs.py` from
`agent/bounds/rules.yaml`. Do not hand-edit." That header is a promise to a
reader that the table below it is what the gate actually enforces.

It was broken. `PROMISE_COOLDOWN` was changed in `rules.yaml` (WHAT_BROKE
#14) and the doc was not regenerated, so `docs/BOUNDS.md` published the old
rule text -- a document whose entire value is being derivable from source,
quietly not derivable from source.

The uncomfortable part: `gen_docs.py --check` already existed, and did
exactly this job, correctly, including the distinction between
deterministic generators and `LEDGER.md` (whose hash chain legitimately
differs every run). Nothing ever invoked it -- not CI, not the suite. The
tool was built and never wired up, which is a more common failure than a
missing tool and harder to notice, because the capability is right there in
the repo looking finished.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]


def _all_rules() -> list[dict]:
    """Both registers. rules.yaml splits them -- `regulatory` (law this
    system must not break) and `stopping` (limits it imposes on itself) --
    and a check that read one and not the other would pass while half the
    gate drifted."""
    loaded = yaml.safe_load((REPO / "agent" / "bounds" / "rules.yaml").read_text(encoding="utf-8"))
    return list(loaded["regulatory"]) + list(loaded["stopping"])


def test_gen_docs_check_reports_no_stale_documents():
    """The repo's own staleness check, finally run by something.

    `--check` compares without writing, so this asserts on the working tree
    rather than quietly repairing it -- a test that regenerates the docs it
    is checking would pass forever and detect nothing.
    """
    result = subprocess.run(
        [sys.executable, str(REPO / "tools" / "gen_docs.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "tools/gen_docs.py --check reports stale generated documentation:\n"
        f"{result.stdout}\n{result.stderr}\n"
        "Run `python tools/gen_docs.py` and commit the result."
    )


def test_every_bounds_rule_id_appears_in_the_generated_table():
    """A rule added to the YAML and never regenerated into the doc leaves
    the doc claiming the gate has fewer rules than it does. Independent of
    the generator, so it still holds if `--check` is ever weakened."""
    ids = [r["id"] for r in _all_rules()]
    published = (REPO / "docs" / "BOUNDS.md").read_text(encoding="utf-8")

    missing = [rule_id for rule_id in ids if f"`{rule_id}`" not in published]
    assert not missing, f"docs/BOUNDS.md does not mention {missing} -- regenerate it"


def test_the_published_rule_text_matches_the_yaml():
    """The exact failure from WHAT_BROKE #14: the rule was edited, the doc
    was not regenerated, and the published `machine:` expression was the old
    one. Compares the collapsed expression, since the generator folds
    whitespace into a table cell (WHAT_BROKE #5)."""
    published = (REPO / "docs" / "BOUNDS.md").read_text(encoding="utf-8")

    stale = []
    for rule in _all_rules():
        expected = re.sub(r"\s+", " ", str(rule["machine"])).strip()
        if expected not in published:
            stale.append(rule["id"])
    assert not stale, (
        f"docs/BOUNDS.md publishes different rule text than agent/bounds/rules.yaml "
        f"for {stale}. Run `python tools/gen_docs.py`."
    )


def test_the_check_does_not_rewrite_the_working_tree():
    """`--check` must compare, not repair. A check that fixes what it finds
    turns a staleness failure into a silent working-tree edit, and the first
    version of this very test did exactly that by passing an argument
    `gen_docs.py` ignores."""
    bounds = REPO / "docs" / "BOUNDS.md"
    before = bounds.read_text(encoding="utf-8")
    subprocess.run(
        [sys.executable, str(REPO / "tools" / "gen_docs.py"), "--check"],
        cwd=REPO, capture_output=True, text=True,
    )
    assert bounds.read_text(encoding="utf-8") == before
