"""RazorpayRail: the real rail. DEVDOC_v6 §5.3.

Built against a live test-mode account, verified 2026-08-30 (see
docs/RAIL_CAPABILITIES.md, generated by tools/probe_rails.py against real
credentials — not assumed from documentation). What's actually confirmed
live versus implemented-but-unverified is marked per method below; nothing
here claims verification it doesn't have.

**The one structural finding worth stating up front**: Razorpay's
Subscription primitive (what `create_mandate` maps to — Plan + Subscription,
the only recurring-payment object this account can create) bills a *fixed*
amount per cycle on Razorpay's own schedule. It is not a variable
"debit up to max_amount, on demand" instrument the way UPI Autopay/eNACH
mandates are, which is what `MandateSpec`/`present_debit` were modelled on
(§12). `present_debit` and `modify_mandate` raise `RailUnavailable` here —
not because the account lacks a capability, but because this build has not
verified any call that presents an on-demand, ad-hoc debit against a
Subscription; billing happens automatically once the customer authenticates
via the subscription's own `short_url`. Confirmed live-verifiable:
`create_order`, `create_payment_link`, `create_invoice`, `create_mandate`
(as Plan+Subscription), `revoke_mandate` (`subscription.cancel`), `fetch`.
`create_refund` is implemented against the documented SDK method but not
live-verified in this pass — refunding requires an actually-captured
payment, which needs a completed checkout (3DS/OTP), not reachable from a
headless script.
"""

from __future__ import annotations

import razorpay
from razorpay.errors import BadRequestError

from agent.money import assert_money
from agent.rails.types import (
    DebitResult,
    Invoice,
    InvoiceSpec,
    LinkSpec,
    Mandate,
    MandateDelta,
    MandateSpec,
    Order,
    OrderSpec,
    PaymentLink,
    RailUnavailable,
    RefundResult,
)


def _mandate_status_from_subscription(raw_status: str) -> str:
    """Razorpay's real subscription statuses (created, authenticated, active,
    pending, halted, cancelled, completed, expired) don't match the
    TrueCommit-internal lifecycle vocabulary SimulatedRail invented to mirror
    §12.5's diagram literally (pending_afa, notified_24h, ...) -- a real,
    useful drift the conformance suite exists to surface, not paper over.
    Mapped conservatively; anything unrecognised passes through as-is rather
    than being silently coerced to a guess."""
    mapping = {
        "created": "created",
        "authenticated": "active",
        "active": "active",
        "pending": "health_defect",
        "halted": "health_defect",
        "cancelled": "revoked",
        "completed": "expired",
        "expired": "expired",
    }
    return mapping.get(raw_status, raw_status)


class RazorpayRail:
    rail_tag = "razorpay"

    def __init__(self, key_id: str, key_secret: str):
        self._client = razorpay.Client(auth=(key_id, key_secret))

    # ---- Live-verified (docs/RAIL_CAPABILITIES.md, 2026-08-30) ----

    def create_order(self, spec: OrderSpec) -> Order:
        raw = self._client.order.create({
            "amount": assert_money(spec.amount_paise, field="spec.amount_paise"),
            "currency": spec.currency,
            "receipt": spec.receipt,
            "notes": spec.notes,
        })
        return Order(
            id=raw["id"], amount_paise=assert_money(raw["amount"], field="order.amount"),
            currency=raw["currency"], status=raw["status"], receipt=raw.get("receipt"),
        )

    def create_payment_link(self, spec: LinkSpec) -> PaymentLink:
        payload = {"amount": assert_money(spec.amount_paise, field="spec.amount_paise"),
                   "currency": "INR", "description": spec.description, "notes": spec.notes}
        if spec.customer_contact or spec.customer_email:
            payload["customer"] = {
                "contact": spec.customer_contact, "email": spec.customer_email, "name": "Customer",
            }
        if spec.expire_by:
            payload["expire_by"] = spec.expire_by
        raw = self._client.payment_link.create(payload)
        return PaymentLink(
            id=raw["id"], short_url=raw["short_url"],
            amount_paise=assert_money(raw["amount"], field="payment_link.amount"), status=raw["status"],
        )

    def create_invoice(self, spec: InvoiceSpec) -> Invoice:
        raw = self._client.invoice.create({
            "type": "invoice",
            "customer": {
                "name": spec.customer_name or "Customer",
                "email": spec.customer_email, "contact": spec.customer_contact,
            },
            "line_items": [{"name": spec.description, "amount": assert_money(spec.amount_paise, field="spec.amount_paise"),
                             "currency": "INR", "quantity": 1}],
            "notes": spec.notes,
        })
        return Invoice(
            id=raw["id"], amount_paise=assert_money(raw["amount"], field="invoice.amount"),
            status=raw["status"], short_url=raw.get("short_url"),
        )

    def create_mandate(self, spec: MandateSpec) -> Mandate:
        """Plan + Subscription -- the only recurring-payment primitive this
        account can create (docs/RAIL_CAPABILITIES.md). A fixed per-cycle
        amount, not a variable "up to max_amount" mandate -- see module
        docstring. `spec.max_amount_paise` becomes the plan's fixed amount."""
        plan = self._client.plan.create({
            "period": "monthly", "interval": 1,
            "item": {"name": "TrueCommit mandate", "amount": assert_money(spec.max_amount_paise, field="spec.max_amount_paise"), "currency": "INR"},
        })
        total_count = len(spec.debit_schedule) if spec.debit_schedule else 12
        sub = self._client.subscription.create({
            "plan_id": plan["id"], "customer_notify": 0, "total_count": total_count,
        })
        return Mandate(
            id=sub["id"], rail="razorpay", max_amount_paise=assert_money(spec.max_amount_paise, field="spec.max_amount_paise"),
            start_at=spec.start_at, end_at=spec.end_at,
            status=_mandate_status_from_subscription(sub["status"]),
            afa_required=spec.afa_required, debit_schedule=list(spec.debit_schedule),
        )

    def revoke_mandate(self, mandate_id: str) -> Mandate:
        raw = self._client.subscription.cancel(mandate_id)
        return Mandate(
            id=raw["id"], rail="razorpay",
            max_amount_paise=assert_money(raw["plan"]["item"]["amount"], field="subscription.plan.item.amount"),
            start_at=str(raw.get("start_at") or ""), end_at=str(raw.get("end_at") or ""),
            status=_mandate_status_from_subscription(raw["status"]), afa_required=True, debit_schedule=[],
        )

    def fetch(self, kind: str, id: str) -> dict:
        # razorpay-python's client attributes are singular (client.order, .payment,
        # .payment_link, .settlement, ...) while callers pass plural kind names
        # (matching SimulatedRail.fetch's own kind vocabulary) -- verified directly
        # against the installed SDK, not assumed (docs/SIMULATOR_PROVENANCE.md §2).
        attr_name = kind[:-1] if kind.endswith("s") else kind
        resource = getattr(self._client, attr_name, None)
        if resource is None or not hasattr(resource, "fetch"):
            raise RailUnavailable(f"fetch:{kind}", "no matching Razorpay resource with a fetch() method")
        try:
            return dict(resource.fetch(id))
        except BadRequestError as exc:
            raise RailUnavailable(f"fetch:{kind}:{id}", str(exc)) from exc

    # ---- Implemented, not live-verified in this pass ----

    def create_refund(self, payment_id: str, reason: str) -> RefundResult:
        """Documented SDK method (client.payment.refund) -- not exercised
        against a real captured payment, since producing one needs a
        completed checkout (3DS/OTP), not reachable headlessly. See module
        docstring."""
        raw = self._client.payment.refund(payment_id, {"notes": {"reason": reason}})
        return RefundResult(
            id=raw["id"], payment_id=payment_id,
            amount_paise=assert_money(raw["amount"], field="refund.amount"), status=raw["status"],
        )

    # ---- Not verified to exist in the shape this Rail's callers assume ----

    def modify_mandate(self, mandate_id: str, delta: MandateDelta) -> Mandate:
        raise RailUnavailable(
            "modify_mandate",
            "no verified live call changes a Subscription's per-cycle amount or expiry "
            "on demand in this build -- see the module docstring's structural finding",
        )

    def present_debit(self, mandate_id: str, amount_paise: int) -> DebitResult:
        raise RailUnavailable(
            "present_debit",
            "Razorpay Subscriptions bill automatically on their own schedule once the "
            "customer authenticates via the subscription's short_url -- no verified call "
            "presents an ad-hoc debit against one on demand (§5.1)",
        )
