#!/usr/bin/env python3
"""Regenerate documentation from source of truth. DEVDOC_v6 §21.

    uv run python tools/gen_docs.py           # write docs/BOUNDS.md, REGULATORY_MAP.md, LEDGER.md
    uv run python tools/gen_docs.py --check    # exit 1 if the committed docs are stale

Documentation that can't drift from the code is a different artifact from
documentation that just happens to be accurate today, so I generate what I
can. Only the three docs below are generated so far — RESULTS.md needs an
actual eval run (§17), and RAIL_CAPABILITIES.md needs tools/probe_rails.py
run against a live account; both now exist too, generated by their own
scripts, not this one.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

from agent.act.actions import HUMAN_GATED_ACTIONS, RAZORPAY_OBJECT_FOR_ACTION
from agent.bounds.engine import default_rules
from agent.diagnose.taxonomy import default_taxonomy
from agent.ledger.models import LedgerEntry
from agent.ledger.store import ChainIntegrityError, Ledger

DOCS_DIR = Path(__file__).resolve().parents[1] / "docs"


def _cell(text: str) -> str:
    """Collapse any embedded newlines/repeated whitespace before putting text in a
    Markdown table cell. YAML's folded (`>-`) scalars only fold same-indentation
    continuation lines -- a more-indented line (used for visual alignment in
    rules.yaml) keeps its newline, which then breaks the table row. Fixed here
    defensively rather than by fighting YAML indentation rules in the source."""
    return " ".join(text.split())


def gen_bounds_md() -> str:
    rules = default_rules()
    regulatory = [r for r in rules if r.kind == "regulatory"]
    stopping = [r for r in rules if r.kind == "stopping"]
    taxonomy = default_taxonomy()

    lines = [
        "# Bounds Register",
        "",
        "Generated by `tools/gen_docs.py` from `agent/bounds/rules.yaml` and "
        "`data/failure_taxonomy.yaml`. Do not hand-edit — edit the source YAML and regenerate.",
        "",
        "## Regulatory bounds (§13.1)",
        "",
        "| id | source | clause_ref | machine | human | test |",
        "|---|---|---|---|---|---|",
    ]
    for r in regulatory:
        clause = r.clause_ref or "—"
        flagged = " **[not yet pinned to the circular text]**" if clause.startswith("TODO") else ""
        lines.append(
            f"| `{r.id}` | {_cell(r.source or '—')} | {_cell(clause)}{flagged} | "
            f"`{_cell(r.expr.source)}` | {_cell(r.human)} | `{r.test}` |"
        )

    lines += [
        "",
        "## Stopping rules (§13.2, as amended by §24.2)",
        "",
        "| id | machine | human | test |",
        "|---|---|---|---|",
    ]
    for r in stopping:
        lines.append(f"| `{r.id}` | `{_cell(r.expr.source)}` | {_cell(r.human)} | `{r.test}` |")

    lines += [
        "",
        "## Decline taxonomy: RETRYABLE / TERMINAL (§11.2)",
        "",
        "Sourced from Razorpay's public error pages — see docs/SIMULATOR_PROVENANCE.md "
        "for exact URLs and the `disposition` semantics (this is *not* the source pages' "
        "own \"is this retryable\" framing; see `data/failure_taxonomy.yaml`'s header comment).",
        "",
        "| code | rail | source | disposition |",
        "|---|---|---|---|",
    ]
    for rail in ("cards", "upi"):
        for code in sorted(taxonomy.permitted_codes(rail)):
            classification = taxonomy.classify(code, rail)
            lines.append(f"| `{code}` | {rail} | {classification.source} | {classification.disposition} |")

    lines += [
        "",
        "## Escalation ladder — human-gated actions (§11.5)",
        "",
        "| action | Razorpay object | gate |",
        "|---|---|---|",
    ]
    for action, obj in RAZORPAY_OBJECT_FOR_ACTION.items():
        gate = "**human**" if action in HUMAN_GATED_ACTIONS else "autonomous (subject to check_bounds)"
        lines.append(f"| `{action.value}` | {obj or '—'} | {gate} |")

    lines += [
        "",
        "## §13.4 — three claims, and none of them is \"compliant\"",
        "",
        "| Artifact | Establishes | Does **not** establish |",
        "|---|---|---|",
        "| **Differential test** (`tests/agent/test_bounds_differential.py`, 5,000 "
        "Hypothesis-generated inputs) | Implementation consistency — the machine rule "
        "and an independently hand-written human twin (`agent/bounds/human_twin.py`) agree | "
        "Correctness against the actual regulation. Same author wrote both. |",
        "| **This document** | Coverage — which clauses are implemented, which are stubbed, "
        "honestly listed | That the implementation reads each clause correctly |",
        "| **Per-clause tests** (`tests/regulatory/`) | Not yet built — every `test:` path "
        "above is a target, not yet a file | — |",
        "",
        "**Compliance requires external review, which I don't have.** "
        "See docs/LIMITATIONS.md.",
        "",
        "## Refusal log",
        "",
        "No eval run has happened yet (§17's four-arm harness isn't built) — the "
        "`bounds_refusals` table this section closes with, per DEVDOC_v6 §13.3, is "
        "empty. This section will be regenerated with real refusals once an arm runs.",
        "",
    ]
    return "\n".join(lines) + "\n"


def gen_regulatory_map_md() -> str:
    rules = [r for r in default_rules() if r.kind == "regulatory"]
    lines = [
        "# Regulatory Map",
        "",
        "Generated by `tools/gen_docs.py` from `agent/bounds/rules.yaml`'s `clause_ref` "
        "and `test` fields. Promoted to Tier 1 (§13.4) — this is the artifact that "
        "actually demonstrates coverage, which is the strongest honest claim available.",
        "",
        "| Clause / source | Rule id | Test | Verdict |",
        "|---|---|---|---|",
    ]
    for r in rules:
        clause = _cell(r.clause_ref or "not recorded")
        verdict = "**NOT PINNED** — clause_ref is a placeholder" if clause.startswith("TODO") else "implemented, not independently reviewed"
        lines.append(f"| {_cell(r.source or '—')} — {clause} | `{r.id}` | `{r.test}` (not yet written) | {verdict} |")

    lines += [
        "",
        "## Honestly not implemented",
        "",
        "| Requirement | Status |",
        "|---|---|",
        "| MSMED Act statutory ladder rungs 5-6 (year-end 43B(h) notice, MSME Samadhaan referral) | Documented, stubbed with a clear NotImplementedError (§14.4) — not implemented |",
        "| Per-clause regulatory tests (`tests/regulatory/`) | Directory exists, no tests written yet |",
        "| Live conformance against a real Razorpay account | **Done** (2026-08-30) — `agent/rails/razorpay_rail.py`, verified in `tests/agent/test_razorpay_rail_live.py` against a live test-mode account (§5.1, §5.4) |",
        "| NACH/eNACH return-code taxonomy | Not sourced yet (data/failure_taxonomy.yaml's `not_yet_sourced` section) |",
        "| `RBI_FPC_HOURS` and `TRAI_DND` clause_refs | Weakest-sourced (`RBI_FPC_HOURS`, secondary summaries only) or unsourced (`TRAI_DND`, still a TODO) rows in this table — re-check before relying on either |",
        "",
    ]
    return "\n".join(lines) + "\n"


def _run_ledger_worked_example() -> tuple[str, str]:
    """Actually run a debtor AT_RISK -> RECOVERED scenario through the real Ledger,
    then actually corrupt a row and run verify_chain(), capturing real output for
    both — not hand-typed illustrations."""
    with tempfile.TemporaryDirectory() as tmp:
        db_path = Path(tmp) / "worked_example.db"
        with Ledger(db_path) as ledger:
            steps = [
                ("INGEST", {"debtor_state_after": "AT_RISK"}),
                ("DIAGNOSE", {"debtor_state_after": "DIAGNOSED"}),
                ("DECIDE", {"debtor_state_after": "ENGAGED"}),
                ("ACT", {"debtor_state_after": "PROMISED"}),
                ("LISTEN", {"debtor_state_after": "INSTRUMENTED"}),
                ("SETTLE", {"debtor_state_after": "RECOVERED", "recovered_paise": 1_200_000}),
            ]
            finalized = [ledger.append(LedgerEntry(actor=actor, debtor_id="debtor_worked_example", outcome=outcome))
                         for actor, outcome in steps]

        worked_example_lines = ["| seq | actor | prev_hash (truncated) | hash (truncated) | outcome |",
                                 "|---|---|---|---|---|"]
        for e in finalized:
            worked_example_lines.append(
                f"| {e.seq} | {e.actor} | `{e.prev_hash[:12]}...` | `{e.hash[:12]}...` | {e.outcome} |"
            )
        worked_example = "\n".join(worked_example_lines)

        # Now actually tamper and actually run the verifier, for real stdout.
        import json
        import sqlite3

        conn = sqlite3.connect(str(db_path))
        row = conn.execute("SELECT body_json FROM ledger WHERE seq = 3").fetchone()
        body = json.loads(row[0])
        body["actor"] = "TAMPERED"
        conn.execute("UPDATE ledger SET body_json = ? WHERE seq = 3", (json.dumps(body),))
        conn.commit()
        conn.close()

        with Ledger(db_path) as ledger:
            try:
                ledger.verify_chain()
                tamper_output = "verify_chain() did not raise -- THIS WOULD BE A BUG"
            except ChainIntegrityError as exc:
                tamper_output = f"ChainIntegrityError: {exc}"

    return worked_example, tamper_output


def gen_ledger_md() -> str:
    worked_example, tamper_output = _run_ledger_worked_example()
    lines = [
        "# Ledger",
        "",
        "Generated by `tools/gen_docs.py`. The worked example and tamper-evidence "
        "output below are from an actual `Ledger` run, not hand-typed illustrations.",
        "",
        "## Row schema",
        "",
        "See `agent/ledger/models.py::LedgerEntry`. `seq`, `ts`, `prev_hash` and `hash` "
        "are assigned by `Ledger.append()` only — never caller-supplied (§15).",
        "",
        "## Replay contract",
        "",
        "`Ledger.replay(debtor_id, until=None)` folds one debtor's slice of the chain "
        "into a `ReplayResult` (`agent/ledger/store.py`). Verified by "
        "`tests/agent/test_shuffled_replay.py` (full pipeline, three shuffles, "
        "identical totals) and `tests/agent/test_ledger.py`.",
        "",
        "## Worked example: a debtor from AT_RISK to RECOVERED",
        "",
        worked_example,
        "",
        "## Tamper evidence — actual output",
        "",
        "Row `seq=3`'s payload was mutated directly in the SQLite file (bypassing the "
        "`Ledger` API entirely), then `verify_chain()` was called:",
        "",
        "```",
        tamper_output,
        "```",
        "",
        "## Deliberately not stored",
        "",
        "Raw card/bank credentials; full inbound message bodies beyond the retention "
        "window; debtor contact details in any exported evidence set; model outputs "
        "rejected at schema validation (logged by reason and count, not content).",
        "",
    ]
    return "\n".join(lines) + "\n"


# BOUNDS.md and REGULATORY_MAP.md are pure functions of static YAML — byte-identical
# on every run, so "stale" (committed content != freshly generated content) is a
# meaningful CI gate for them. LEDGER.md's worked example re-runs a live Ledger with
# a real clock and real hashes every invocation, so it is *never* byte-stable across
# runs by design — checking it the same way would make --check permanently fail.
DETERMINISTIC_GENERATORS = {
    "BOUNDS.md": gen_bounds_md,
    "REGULATORY_MAP.md": gen_regulatory_map_md,
}
FRESH_EACH_RUN_GENERATORS = {
    "LEDGER.md": gen_ledger_md,
}


def main() -> int:
    check_only = "--check" in sys.argv
    stale: list[str] = []

    for filename, generator in DETERMINISTIC_GENERATORS.items():
        content = generator()
        path = DOCS_DIR / filename
        if check_only:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                stale.append(filename)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path}")

    for filename, generator in FRESH_EACH_RUN_GENERATORS.items():
        path = DOCS_DIR / filename
        if check_only:
            # Regenerate-and-verify-it-doesn't-crash is the meaningful check here,
            # not a byte diff — the content is supposed to differ every run.
            try:
                generator()
            except Exception as exc:  # noqa: BLE001
                print(f"STALE: {filename}'s generator raised {exc!r} — the worked "
                      f"example no longer runs against the current code.", file=sys.stderr)
                stale.append(filename)
        else:
            path.write_text(generator(), encoding="utf-8")
            print(f"wrote {path}")

    if check_only:
        if stale:
            print(f"STALE: {', '.join(stale)} — run 'uv run python tools/gen_docs.py' "
                  f"and commit the result.", file=sys.stderr)
            return 1
        print("All generated docs are up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
