#!/usr/bin/env python3
"""Write docs/evidence/REAL_BATCH.md from a run of tools/run_real_batch.py.

Every status in the report is **fetched back from Razorpay**, not read out
of the local record written at creation time. That distinction is the whole
point: the local record says what the agent believed it did, and the fetch
says what the rail actually holds. A report that only quotes the former
proves the code ran, not that anything happened.

    uv run python tools/run_real_batch.py --n 10   # create
    ... pay some of the links ...
    uv run python tools/report_real_batch.py       # verify + write

Safe to re-run: it re-fetches every invoice each time, so running it again
after paying more links updates the counts.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from agent.rails.types import RailUnavailable  # noqa: E402
from eval.stats import wilson_interval  # noqa: E402
from tools.run_real_batch import STATE_PATH, _client, _load_dotenv  # noqa: E402

REPORT_PATH = REPO_ROOT / "docs" / "evidence" / "REAL_BATCH.md"

PAID_STATUSES = {"paid"}


def fetch_statuses(results: list[dict]) -> list[dict]:
    rail = _client()
    out = []
    for row in results:
        record = dict(row)
        ref = row.get("external_ref")
        if not ref:
            record["live_status"] = None
            out.append(record)
            continue
        try:
            raw = rail.fetch("invoices", ref)
            record["live_status"] = raw.get("status")
            record["amount_paid_paise"] = raw.get("amount_paid")
            record["live_payment_id"] = raw.get("payment_id")
        except RailUnavailable as exc:
            record["live_status"] = f"fetch failed: {exc}"
        out.append(record)
        print(f"  {record['invoice_id']}  {ref}  {record.get('live_status')}")
    return out


def build_report(state: dict, rows: list[dict]) -> str:
    n = len(rows)
    created = [r for r in rows if r.get("external_ref")]
    refused = [r for r in rows if r.get("bounds_passed") is False]
    errored = [r for r in rows if r.get("error")]
    paid = [r for r in rows if r.get("live_status") in PAID_STATUSES]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    recovered_paise = sum(r.get("amount_paid_paise") or 0 for r in paid)

    parts = [
        "# A real batch: agent decisions that created real objects",
        "",
        f"*Generated by `tools/report_real_batch.py` at {now}. Do not edit by hand.*",
        "",
        "**This measures pipeline completeness, not a recovery rate.** The invoices "
        "below were paid by me, on a test-mode account, because I wanted to see the "
        "capture path run. That says nothing whatever about whether real debtors pay. "
        "Anyone reading a percentage out of this file is reading it wrong; the only "
        "numbers in this project that speak to recovery are the counterfactual arms "
        "in `docs/RESULTS.md`, and those are simulated.",
        "",
        "What it does establish is the one thing `DRY_RUN_BATCH.md` structurally "
        "cannot: that a decision this agent makes turns into an object on a real "
        "rail, more than once, without a human in the loop between the two.",
        "",
        "## What ran",
        "",
        f"| | |",
        "|---|---|",
        f"| decisions | {n} |",
        f"| created a real Razorpay object | {len(created)} |",
        f"| refused by `check_bounds()` | {len(refused)} |",
        f"| rail errors | {len(errored)} |",
        f"| **paid (status fetched back from Razorpay)** | **{len(paid)}** |",
        f"| value captured | Rs {recovered_paise / 100:,.2f} |",
        f"| ledger hash chain verified | {state.get('ledger_chain_verified')} |",
        f"| account | `{state.get('key_id', '')[:16]}...` (test mode) |",
        "",
        "Every `inv_*` id below is real and independently checkable in the Razorpay "
        "dashboard for that account. The status column is **fetched live at report "
        "time**, not copied from what the agent recorded when it created the object.",
        "",
        "## Every decision",
        "",
        "| invoice | diagnosis class | action chosen | gate | Razorpay id | status |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        # A rail error is not a gate refusal, and rendering it as one would
        # blame check_bounds() for something it never saw. `bounds_passed` is
        # absent on an errored row, so a plain falsy test prints "REFUSED"
        # for a row the gate never ran on -- which is exactly what the first
        # version of this table did, contradicting its own summary two rows
        # above it.
        if r.get("error"):
            gate = "n/a — rail error before dispatch"
        elif r.get("bounds_passed"):
            gate = "pass"
        else:
            gate = "REFUSED: " + ", ".join(r.get("refusal_reasons") or ["(no reason recorded)"])
        parts.append(
            f"| `{r['invoice_id']}` | {r['class']} | {r.get('action_type') or '-'} | "
            f"{gate} | `{r.get('external_ref') or '-'}` | {r.get('live_status') or '-'} |"
        )

    if errored:
        parts += [
            "",
            "### The five rail errors",
            "",
            "All five are the same thing, and it is a real finding rather than a "
            "flaky run:",
            "",
            "```",
            *[f"{r['invoice_id']}  {r['error']}" for r in errored],
            "```",
            "",
            "**Razorpay rate-limits invoice creation, and this batch had no backoff.** "
            "Five creates in rapid succession went through; the sixth did not. Nothing "
            "in the test suite caught it because `SimulatedRail` has no rate limit — "
            "there is no such failure to simulate. See `docs/WHAT_BROKE.md` #28.",
            "",
            "What did hold, on a run that was half errors: the per-row exception "
            "handler recorded each failure with its type instead of stranding "
            "half-created objects, the batch continued, and the ledger hash chain "
            "verified afterwards.",
        ]

    if paid:
        interval = wilson_interval(len(paid), len(created)) if created else None
        parts += [
            "",
            "## On the fraction",
            "",
            f"{len(paid)} of {len(created)} created invoices were paid"
            + (f" ({interval.as_pct()} with a Wilson interval)" if interval else "")
            + ". That interval is arithmetic, not evidence: I chose which links to "
            "pay. It is printed only so the number is not mistaken for a measured "
            "conversion rate — the denominator is my own free time, not a population "
            "of debtors.",
        ]

    parts += [
        "",
        "## Why Family B, and why that is a choice about the input",
        "",
        "Every row is a Family B (administrative blocker) diagnosis. Two honest "
        "constraints meet there:",
        "",
        "* Family B's correct repair genuinely *is* reissuing the document — "
        "`_decide_next_step` maps it to `REISSUE_ARTIFACT`, which calls "
        "`rail.create_invoice()`.",
        "* This account's payment-link allowance counts **lifetime creates** and is "
        "exhausted (`docs/WHAT_BROKE.md`). A Family A batch would route to "
        "`CREATE_PAYMENT_LINK` and measure Razorpay's quota rather than this "
        "pipeline. Invoices are not capped — 48 exist on the account and creation "
        "still works.",
        "",
        "So the **population** was chosen; the **decision** was not. EV is computed by "
        "the fitted model, `check_bounds()` can still refuse, and whatever the agent "
        "picked is what executed and what is recorded above — including refusals and "
        "including errors.",
        "",
        "## Why subscriptions are not in this batch",
        "",
        "Because the loop cannot close on them, and saying so is more useful than "
        "hiding it. A mandate can be **created** on this account — the "
        "`rzp.io/rzp/...` authorization links in `docs/evidence/REAL_SCENARIOS.md` "
        "are real. It cannot be **debited**: a Razorpay Subscription bills a fixed "
        "amount on its own schedule, and this account exposes no API to present a "
        "debit on demand, so `present_debit` and `modify_mandate` raise "
        "`RailUnavailable` rather than guess.",
        "",
        "Invoices can be paid; mandates cannot be debited. That is the structural "
        "gap in the detect → repair → present → capture loop, it is the honest "
        "reason this batch is invoices, and it is documented at length in "
        "`docs/LIMITATIONS.md`.",
        "",
        "## What is still not proven here",
        "",
        "* **That debtors pay.** See the first paragraph.",
        "* **That test mode predicts production.** A test-mode capture clears because "
        "Razorpay says so, not because a bank moved money.",
        f"* **Anything at n={n}.** This is a completeness check, not a measurement. "
        "The statistical work in this project is at n=500 and simulated "
        "(`docs/RESULTS.md`); this is at n=10 and real. Neither substitutes for the "
        "other, and the project claims both only for what each one covers.",
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    _load_dotenv()
    if not STATE_PATH.exists():
        sys.exit(f"no batch state at {STATE_PATH} -- run tools/run_real_batch.py first")
    state = json.loads(STATE_PATH.read_text(encoding="utf-8"))
    print(f"re-fetching {len(state['results'])} invoices from Razorpay...\n")
    rows = fetch_statuses(state["results"])
    state["results"] = rows
    state["verified_at"] = datetime.now(timezone.utc).isoformat()
    STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")
    REPORT_PATH.write_text(build_report(state, rows), encoding="utf-8")
    paid = sum(1 for r in rows if r.get("live_status") in PAID_STATUSES)
    print(f"\n{paid} paid of {sum(1 for r in rows if r.get('external_ref'))} created")
    print(f"wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
